// src/components/views/goodbye/GoodbyeComponent.tsx
import { Link } from 'react-router-dom';

import { Route } from '~/router';
import { useI18n } from '~/utils/i18n.utils';

import styles from './GoodbyeComponent.module.scss';

export function GoodbyeComponent() {
  const i18n = useI18n('goodbye');

  return (
    <div className={styles.text}>
      <span className={styles.title}>{i18n('app_name', 'global')}</span>
      <Link to={Route.Hello}>{i18n('title')}</Link>
    </div>
  );
}

// src/components/views/goodbye/GoodbyeComponent.vue
<script lang="ts" setup>
import { RouterLink } from 'vue-router';

import { Route } from '~/router';
import { useI18n } from '~/utils/i18n.utils';

const i18n = useI18n('goodbye');
</script>

<template>
  <div class="text">
    <span class="title">{{ i18n('app_name', 'global') }}</span>
    <RouterLink :to="Route.Hello">
      {{ i18n('title') }}
    </RouterLink>
  </div>
</template>

<style lang="scss" scoped>
.text {
  display: flex;
  flex-direction: column;
  align-items: center;
  align-self: center;
  justify-content: center;
  width: 100%;
  height: 100%;

  .title {
    margin-bottom: 2rem;
  }

  a {
    color: white;
    text-decoration: none;
    outline: none;
  }
}
</style>
